### ISSUE TITLE
ERROR: Service 'tabbyapi' failed to build : Build failed

### ISSUE THREAD

**Issue by okrueger3** [homebrewltd/ichigo-demo#8]
I've tried to setup the docker image. 
_sudo docker-compose build_

leads always to 
_
Building tabbyapi
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/home/ichigo-demo/docker/tabbyAPI-personal-fork/docker: no such file or directory_

The folder _/ichigo-demo/docker/tabbyAPI-personal-fork$_ is empty. 

I would appreciate any advice. Thanks

**Comment by nguyenhoangthuan99** [comment]
can you try init submodule for `tabbyAPI-personal-fork`

```
git submodule init
git submodule update
```
after that 2 commands, the `tabbyAPI-personal-fork` will be pull

**Comment by okrueger3** [comment]
Thanks, that solved the problem!

**Comment by nguyenhoangthuan99** [comment]
If you can build and run it successfully, please close this issue.
